apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: demo-app
          image: ghcr.io/runhub-dev/demo-app:{{ .Values.commit }}
          ports:
            - containerPort: 3000
