apiVersion: batch/v1
kind: Job
metadata:
  name: buildkit
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: buildkit
          image: "moby/buildkit:v0.19.0@sha256:14aa1b4dd92ea0a4cd03a54d0c6079046ea98cd0c0ae6176bdd7036ba370cbbe"
          command: ["/bin/sh", "-c"]
          args:
            - |
              buildctl-daemonless.sh build \
              --frontend=dockerfile.v0 \
              --opt context=https://github.com/runhub-dev/demo-app.git#{{ .Values.commit }} \
              --output type=image,name=ghcr.io/runhub-dev/demo-app:{{ .Values.commit }},push=true
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-config
              mountPath: /root/.docker
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
