apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/runhub-dev/demo-infra.git
    targetRevision: main
    path: charts/demo-app
    helm:
      parameters:
        - name: commit
          value: 74a3966b8c3b33c7d3d855a57e9ebb46db2836ba
  destination:
    name: in-cluster
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
